### PR TITLE
CAM 12 - Modal for sensitive data information

### PR DESCRIPTION
**Pull request by dfrojas**
## Description

This PR adds a modal displaying information about sensitive data to download. This modal is displayed when the user does click on the Data Download tab.

## How to testing

You need to add the flag `ENABLE_SENSITIVE_DATA_MSG_ON_DASHBOARD` in settings or in site_configuration

## Screenshots

screenshot from 2018-01-26 11-36-06

screenshot from 2018-01-26 11-36-21

## Reviewers

- [ ] @felipemontoya 
- [ ] @jagonzalr

## Post-review

- [ ] Squash the commits

### CODE REVIEW

**Comment by jagonzalr** [comment]
@dfrojas the `jquery.leanModal` where does that come from?

**Comment by dfrojas** [comment]
@jagonzalr This comes from `common/static/js/vendor/jquery.leanModal.js`. We follow the same rule (path) as the staff debug buttons: `lms/templates/courseware/xqa_interface.html`

**Comment by jagonzalr** [comment]
Ahhh @dfrojas it is already part of the codebase. Ok code looks good. I'm gonna test it in my local machine and put more comments if necessary :)

**Comment by jagonzalr** [comment]
@dfrojas I'm not gonna merge this but it is approved cc @felipemontoya

**Comment by jagonzalr** [comment]
@dfrojas Campus came back saying that the disclaimer is not getting display on the csv of the reports. I'm trying to run it on my local machine but I'm having trouble with the workers and can't get the reports. Could you check this out and see if all the reports are getting the disclaimer? I'll add the generated csv from Campus on Slack cc @felipemontoya

**Comment by dfrojas** [comment]
@jagonzalr Are you sure that they are testing in dro/CAM-11 branch? CAM-12 (this branch) only display a modal, CAM-11 is the branch that adds the feature of the disclaimer directly in the reports.

**Pull request closed without merging**
