### PR TITLE
Jfa/restricted enrolled students report

### PR DESCRIPTION
**Pull request by jfavellar90**
Enabling download of enrolled users reports only including GDPR compliant fields.

@nicovanniekerk please take a look on this before deploying to dev environment, just to agree that changes make sense

### CODE REVIEW

**Comment by jfavellar90** [comment]
@nicovanniekerk maybe other aspect to consider is that, on the front end, the message the instructor see when downloading the report is "Click to generate a CSV file of all students enrolled in this course, along with profile information such as email address and username", but a restricted report will only contain the email field (GDPR_MODE enabled). should I change the text based on?

**Comment by nicovanniekerk** [comment]
@jfavellar90 yes please, change the message according to the data that will be present in the report, please also add the "GDPR_MODE_PROFILE_DOWNLOAD" setting to the configuration repo, as to allow it to be put in the server-vars.yml file. I will log the request for consola to be updated to add the setting to all microsites.

@jagonzalr please add the "GDPR_MODE_PROFILE_DOWNLOAD" setting to consola and default it to true for now. i will log on celoxis tomorrow morning quick

**Comment by jfavellar90** [comment]
@nicovanniekerk ready with the messages

**Comment by jfavellar90** [comment]
@diegomillan can you help with a revision?

**Review by diegomillan — APPROVED** [review]
LGTM :+1:

**Pull request merged**
